### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by uedvt359** [fragtastic/sentinelone-api-python#3]
Hi, first of all thank you for writing this neat API wrapper!

We'd like to contribute some code to this, mostly in the form of more supported endpoints. Can you please add a free license?

I'd also like to loop in @austin-manuel, who has added some endpoints in their own fork, and which I'd like to include in our Pull Request under whichever license you can agree on.

Thanks!

**Comment by rstory** [comment]
I'd also like a definitive license to be added. Github has a helpful page on licenses here: https://choosealicense.com/

They explain what not having a license means:  "If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software."

This project looks very useful, and I'd love to use it to make my job easier. But I can't do that now because there is no licesne. :-(

**Comment by fragtastic** [comment]
Thanks for bringing this back up.

GNU LGPLv3 looks like it would be the best option.
I don't imagine there would be any complaints under this license.

**Comment by rstory** [comment]
That would be great. Could you update the project github 'about' section and the README to reflect you license choice? Thanks!

**Comment by fragtastic** [comment]
Commit 44820fdabed9ecd92da2ac964493a2be67bc0678 adds standalone license file.
